name: Publish on release creation
on:
  release:
    types:
      - published
  repository_dispatch:
    types:
      - release-made
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          # from tyrannosaurus "pymetaversion"; actual versions are handled in Tox
          python-version: 3.9
      - name: Install build meta-dependencies
        run: |
          pip install poetry
      - name: Build sdists and wheels with Poetry
        run: |
          poetry build
          poetry install
      - name: Build the Docker image
        run: |
          docker build .
      # Remove this section if you don't want to publish to Github packages:
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/${{ github.event.repository.name }}
          tag_with_ref: true
      - name: Attach artifacts to the Github release
        uses: skx/github-action-publish-binaries@master
        with:
          args: 'dist/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to PyPi
        run: |
          poetry publish -vv --username __token__ --password ${{ secrets.PYPI_TOKEN }}
